screen -dmS server ./server.sh
screen -dmS reducer ./reducer.sh
screen -dmS eth-btc ./run-eth-btc.sh
#screen -dmS btc-usd ./run-btc-usd.sh
#screen -dmS eth-usd ./run-eth-usd.sh
screen -dmS ltc-btc ./run-ltc-btc.sh
#screen -dmS ltc-usd ./run-ltc-usd.sh
#screen -dmS btc-eur ./run-btc-eur.sh
#screen -dmS btc-gbp ./run-btc-gbp.sh
